const APP_CONFIG = {
    SERVER_KEY: "AAAAHEXZsPs:APA91bFbJuMt6bFgKDj8AAqUEoOKd2IL4ZElXBmAtc_rD93Or8KmVtdErdVPOjZ6jgsSbXV_IShHY44DI5UvNi-6phQmEMAFUlydGZ7RCAffU7JHCEliqtrF8AyiZpMliaTayqQ_sA60"
};

module.exports = APP_CONFIG;